# Generated by Django 3.1.5 on 2021-01-04 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Filter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('filter', models.TextField()),
                ('order', models.IntegerField(choices=[(1, 'مهم'), (2, 'متوسط'), (3, 'بی اهمیت')], default=3)),
            ],
        ),
    ]
