# Generated by Django 3.1.5 on 2021-01-06 20:42

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('filters', '0002_filter_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filter',
            name='data',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
    ]
