# Generated by Django 3.1.5 on 2021-01-30 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filters', '0003_auto_20210106_2042'),
    ]

    operations = [
        migrations.AddField(
            model_name='filter',
            name='category',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='filter',
            name='data',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
