# Generated by Django 3.1.5 on 2021-02-02 18:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('filters', '0004_auto_20210130_0314'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='filter',
            name='data',
        ),
    ]
