# Generated by Django 3.1.5 on 2021-01-04 11:16

import charts.models
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('order', models.IntegerField(default=charts.models.last_order)),
                ('category', models.IntegerField(choices=[(1, 'دیدبان'), (2, 'بنیادی'), (3, 'تکنیکال')], default=1)),
                ('data', models.TextField(blank=True, default='', editable=False)),
                ('last_update', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('r_file', models.FileField(blank=True, max_length=500, null=True, upload_to=charts.models.upload_to)),
            ],
        ),
    ]
