# Generated by Django 3.1.5 on 2021-01-04 22:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('charts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chart',
            name='last_update',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
