# Generated by Django 3.1.5 on 2021-01-04 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charts', '0003_auto_20210104_2249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chart',
            name='data',
            field=models.TextField(default='.'),
        ),
    ]
