# Generated by Django 3.1.5 on 2021-01-05 17:45

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('charts', '0004_auto_20210104_2250'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chart',
            name='data',
            field=django.contrib.postgres.fields.jsonb.JSONField(default='.'),
        ),
    ]
